swagger: '2.0'
info:
  version: 1.0.0
  title: BookMonkey2 API
  description: |
    **DEMO**

    This is a simple backend for the Angular 2.0 Demo "Book Monkey"

    See [angular2buch.de](https://angular2buch.de/) for more information.
#host: book-monkey2-api.angular2buch.de
#host: localhost:3000
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
tags:
- name: book
  description: BookMonkey2 books with thumbnails
paths:
  /books:
    get:
      tags:
        - book
      summary: Get all books
      responses:
        200:
          description: List of all books
          schema:
            title: Books
            type: array
            items:
              $ref: '#/definitions/Book'


  /book:
    post:
      tags:
        - "book"
      summary: Creates a new book
      parameters:
        - name: book
          in: body
          description: A new book to be stored
          schema:
            $ref: '#/definitions/Book'
          required: true
      responses:
        201:
          description: Book was created
        400:
          description: Invalid data
        409:
          description: Book does already exist

  /book/{isbn}:

    get:
      tags:
      - book
      summary: Returns a single book
      parameters:
        - name: isbn
          in: path
          type: string
          description: ISBN of the book
          required: true
      responses:
        200:
          description: Sends the pet with pet Id

    put:
      tags:
      - book
      summary: Updates an existing book
      description: Requires a full book entry, ISBN in query and body must match
      parameters:
        - name: isbn
          in: path
          description: ISBN of the book to update
          required: true
          type: string
        - name: book
          in: body
          description: An existing book to update
          schema:
            $ref: '#/definitions/Book'
          required: true
      responses:
        200:
          description: Book was updated
        400:
          description: Invalid data
        404:
          description: Book does not exist

    delete:
      tags:
      - book
      summary: Deletes a book
      parameters:
        - name: isbn
          in: path
          description: ISBN of the book to delete
          required: true
          type: string
      responses:
        200:
          description: Book was deleted or did not exist


definitions:
  Book:
    type: object
    required:
    - isbn
    - title
    properties:
      isbn:
        type: string
        example: 999-9-99999-999-9
        description: ISBN, which is used as identifier
      title:
        type: string
        example: Angular2
        description: Title of the book
      authors:
        type: array
        items:
          type: string
          example:
            - Gregor Woiwode
            - Ferdinand Malcher
            - Danny Koppenhagen
            - Johannes Hoppe
        description: List of all authors of the book
      subtitle:
        type: string
        description: Subtitle of the book
      rating:
        type: integer
        format: int32
        example: 5
        description: Rating 'in starts' of the book, from one star (bad) to five stars (great)
      published:
        type: string
        format: date-time
        example: 2016-06-01T00:00:00.000Z
        description: date-time as defined by RFC3339 (http://www.ietf.org/rfc/rfc3339.txt) - like new Date().toISOString();
      description:
        type: string
        description: Short description of the book
      thumbnails:
        type: array
        items:
          $ref: "#/definitions/Thumbnail"
        description: Images of the book, which are used as thumbnails
  Thumbnail:
    type: object
    required:
    - url
    - title
    properties:
      url:
        type: string
        example: https://angular2buch.de/angular2buch.jpg
        description: Image to display
      title:
        type: string
        example: Front Cover
        description: Caption of the image
